# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == "Zeros":
        return np.zeros(shape=shape)
    elif mode == "Ones":
        return np.ones(shape=shape)
    elif mode == "Full":
        return np.full(shape=shape, fill_value=value)
    elif mode == "Identity":
        return np.identity(n=shape)

# example usage
array_factory("Identity", shape=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        # arr = np.array(data1)

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = np.reshape(arr1, shape=(new_shape[0], new_shape[1]))

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.append(arr=reshaped_arr1, values=arr2, axis=0)
        

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

# example usage
data1 = [1, 2, 3, 4, 5, 6]
data2 = [[7, 8, 9], [10, 11, 12]]
new_shape = (2, 3)
secure_reshape_and_stack(data1, data2, new_shape)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [17]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1, shape=None):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr.reshape(shape) if shape else modified_arr

# example usage
data = [10, 25, 30, 45, 50]
threshold_value = 30
apply_threshold(data, threshold_value)

array([10, 25, -1, -1, -1])

TestCase

In [ ]:
# Regional Branch A (Flat sales data)

branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)

branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B

combined_report = secure_reshape_and_stack(branch_a, branch_b, new_shape=(2, 3))
print(combined_report)

print("================")

# Resulting shape: (4, 3)

final_report = apply_threshold(combined_report, threshold=3, replacement_value=-1, shape=(4, 3))
print(final_report)

# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [ ]:
# test apply_threshold function

v= np.array([1,2,3])
apply_threshold(v,2,-20)

array([  1, -20, -20])