In [ ]:
# for install
# %pip install numpy

In [42]:
# using numpy
import numpy as np

In [43]:
list_data = [1, 2, 3]

vector_data_1 = np.array([10, 20, 30])
vector_data_2 = np.array([40, 50, 60])

print("List Data: ", list_data)

print("=================================")

print("Vector Data 1: ", vector_data_1)

print("=================================")

print("Vector Data 2: ", vector_data_2)

List Data:  [1, 2, 3]
Vector Data 1:  [10 20 30]
Vector Data 2:  [40 50 60]


In [44]:
vector_sum = vector_data_1 + vector_data_2
print("Sum of Vector Data 1 and Vector Data 2: ", vector_sum)

print("=================================")

vector_multiply = vector_data_1 * vector_data_2
print("Element-wise Multiplication of Vector Data 1 and Vector Data 2: ", vector_multiply)

print("=================================")

vector_dot_product = vector_data_1.dot(vector_data_2)
print("Dot Product of Vector Data 1 and Vector Data 2: ", vector_dot_product)

print("=================================")

vector_scaled = vector_data_1 * 2
print("Vector Data 1 scaled by 2: ", vector_scaled)

Sum of Vector Data 1 and Vector Data 2:  [50 70 90]
Element-wise Multiplication of Vector Data 1 and Vector Data 2:  [ 400 1000 1800]
Dot Product of Vector Data 1 and Vector Data 2:  3200
Vector Data 1 scaled by 2:  [20 40 60]


In [45]:
matrix_data_1 = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

matrix_data_2 = np.array([[9, 8, 7],
                        [6, 5, 4],
                        [3, 2, 1]])

print("================= Matrix Operations ================")

print("Matrix Addition: \n", matrix_data_1 + matrix_data_2) # each element addition

print("=================================")

print("Matrix Subtraction: \n", matrix_data_1 - matrix_data_2) # each element subtraction

print("=================================")

print("Matrix Multiplication (dot product): \n", matrix_data_1.dot(matrix_data_2)) # matrix multiplication (1st row 1st col, 1st row 2nd col, etc.)

print("=================================")

print("Element-wise Multiplication: \n", matrix_data_1 * matrix_data_2) # each element multiplication

print("=================================")

================= Matrix Operations ================
Matrix Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Subtraction: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication (dot product): 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise Multiplication: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [46]:
# ndim property and np.ndim() function are used to get the number of dimensions of an array.
print("Dimensions of matrix_data_1: ", matrix_data_1.ndim) # Output: 1 as proberty

print("=================================")

print("Dimensions of matrix_data_1: ", np.ndim(matrix_data_1)) # Output: 1 as function

Dimensions of matrix_data_1:  2
Dimensions of matrix_data_1:  2


In [47]:
# shape property and np.shape() function are used to get the shape of an array.
print("Shape of matrix_data_1: ", matrix_data_1.shape) # Output:

print("=================================")

print("Shape of matrix_data_1: ", np.shape(matrix_data_1)) # Output:

Shape of matrix_data_1:  (3, 3)
Shape of matrix_data_1:  (3, 3)


In [48]:
# reshape() function is used to change the shape of an array without changing its data.
reshaped_matrix = matrix_data_1.reshape(1, 9) # Reshaping to 1 row and 9 columns

print("Reshaped Matrix (1 x 9): ", reshaped_matrix) # Output: row vector with 9 elements

Reshaped Matrix (1 x 9):  [[1 2 3 4 5 6 7 8 9]]


In [49]:
# Example of reshaping a vector to a matrix
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape(2, 3)  # Reshaping to 2 rows and 3 columns, must match total elements

print("Reshaped Vector to Matrix (2 x 3): \n", mat) # Output: 2 x 3 matrix

print("=================================")

print("Rows: ", mat.shape[0], ", Columns: ", mat.shape[1]) # used to get rows and columns

Reshaped Vector to Matrix (2 x 3): 
 [[1 2 3]
 [4 5 6]]
Rows:  2 , Columns:  3


In [50]:
mat = vec[:, None]  # Converting to a column vector
print("Column Vector: \n", mat)

print("=================================")

mat = vec[None, :]  # Converting to a row vector
print("Row Vector: \n", mat)

Column Vector: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Row Vector: 
 [[1 2 3 4 5 6]]


In [51]:
# dtype property is used to get the data type of an array
print("Data type of vector_data_1: ", vector_data_1.dtype)

print("=================================")

print("Data type of matrix_data_1: ", matrix_data_1.dtype)

Data type of vector_data_1:  int64
Data type of matrix_data_1:  int64


In [52]:
# priority of data types: object < string < float < int < bool
vec_mixed = np.array([1, 2.5, 3, 1])

print("Data type of mixed vector: ", vec_mixed.dtype) # Output: string (all elements converted to string)

Data type of mixed vector:  float64


In [53]:
vec_mixed = vec_mixed.astype(int)  # Converting back to object type

print("after converting back to int: ", vec_mixed)

print("=================================")

print("Data type after converting back to object: ", vec_mixed.dtype)

after converting back to int:  [1 2 3 1]
Data type after converting back to object:  int64
