# NumPy

**NumPy (Numerical Python)** is an open-source Python library that is widely used in science and engineering.

The NumPy library provides powerful **multidimensional array data structures**, including the homogeneous, N-dimensional `ndarray`. It also offers a large collection of functions that operate efficiently on these data structures, enabling fast mathematical and numerical computations.

---

In [1]:
# For install

# %pip install numpy

In [2]:
# After installing NumPy, it may be imported into Python code like

import numpy as np

In [3]:
# List Vs. Array

list_data = [1, 2, 3]

vector_data_1 = np.array([10, 20, 30])
vector_data_2 = np.array([40, 50, 60])

print("List Data: \n", list_data)

print("=================================")

print("Vector Data 1: \n", vector_data_1)

print("=================================")

print("Vector Data 2: \n", vector_data_2)

print("=================================")

List Data: 
 [1, 2, 3]
Vector Data 1: 
 [10 20 30]
Vector Data 2: 
 [40 50 60]


In [4]:
# Vector and its Operations

print("================= Vector Operations ================")

vector_sum = vector_data_1 + 2
print("Sum of Vector Data 1 and Vector Data 2: \n", vector_sum)

print("=================================")

vector_multiply = vector_data_1 * vector_data_2
print("Element-wise Multiplication of Vector Data 1 and Vector Data 2: \n", vector_multiply)

print("=================================")

vector_dot_product = vector_data_1.dot(vector_data_2)
print("Dot Product of Vector Data 1 and Vector Data 2: \n", vector_dot_product)

print("=================================")

vector_scaled = vector_data_1 * 2
print("Vector Data 1 scaled by 2: \n", vector_scaled)

print("=================================")

================= Vector Operations ================
Sum of Vector Data 1 and Vector Data 2: 
 [12 22 32]
Element-wise Multiplication of Vector Data 1 and Vector Data 2: 
 [ 400 1000 1800]
Dot Product of Vector Data 1 and Vector Data 2: 
 3200
Vector Data 1 scaled by 2: 
 [20 40 60]


In [5]:
# Intial placeholders

# 1. Create an array of zeros (3 rows, 4 columns)
a = np.zeros((3,4)) 

# 2. Create an array of ones (3D array: 2 layers, 3 rows, 4 columns)
b = np.ones((2,3,4), dtype=np.int16) 

# 3. Create an array of values from 10 to 24 (step of 5)
c = np.arange(10, 25, 5) 

# 4. Create 9 evenly spaced values between 0 and 2 (inclusive)
d = np.linspace(0, 2, 9) 

# 5. Create a 2x2 constant array filled with the number 7
e = np.full((2,2), 7) 

# 6. Create a 2x2 identity matrix
f = np.eye(2) 

g = np.identity(2)

# 7. Create a 2x2 array with random float values between 0 and 1
h = np.random.random((2,2)) 

# 7. Create a 2x2 array with random integer values between 4 and 7
i = np.random.randint(4, 7, size=(2, 2))

# 8. Create an "empty" array (contains whatever was in memory)
j = np.empty((3,2)) 

k = np.repeat(i, 3, axis=1)

In [6]:
print("================= Intial placeholder ================")

print("Zeros Array (a):\n", a)

print("=================================")

print("Ones Array (b):\n", b)

print("=================================")

print("Arange Array (c):", c)

print("=================================")

print("Linspace Array (d):", d)

print("=================================")

print("Full Array (e):\n", e)

print("=================================")

print("Identity Matrix (f):\n", f)

print("=================================")

print("Random Array (g):\n", g)

print("=================================")

print("Empty Array (h):\n", h)

print("=================================")

================= Intial placeholder ================
Zeros Array (a):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array (b):
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
Arange Array (c): [10 15 20]
Linspace Array (d): [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Full Array (e):
 [[7 7]
 [7 7]]
Identity Matrix (f):
 [[1. 0.]
 [0. 1.]]
Random Array (g):
 [[1. 0.]
 [0. 1.]]
Empty Array (h):
 [[0.77869396 0.33818273]
 [0.80498411 0.6556603 ]]


In [7]:
# Matrix and its Operations

matrix_data_1 = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

matrix_data_2 = np.array([[9, 8, 7],
                          [6, 5, 4],
                          [3, 2, 1]])

print("================= Matrix Operations ================")

print("Matrix Addition: \n", matrix_data_1 + matrix_data_2) # each element addition

print("=================================")

print("Matrix Subtraction: \n", matrix_data_1 - matrix_data_2) # each element subtraction

print("=================================")

print("Matrix Multiplication (dot product): \n", matrix_data_1.dot(matrix_data_2)) # matrix multiplication (1st row 1st col, 1st row 2nd col, etc.)

print("=================================")

print("Element-wise Multiplication: \n", matrix_data_1 * matrix_data_2) # each element multiplication

print("=================================")

print("Determinant: \n", np.linalg.det(matrix_data_2))

print("=================================")

================= Matrix Operations ================
Matrix Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Subtraction: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication (dot product): 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise Multiplication: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Determinant: 
 0.0


In [8]:
# ndim property and np.ndim() function are used to get the number of dimensions of an array.

print("Dimensions of matrix_data_1: ", matrix_data_1.ndim) # Output: 2 as property

print("=================================")

print("Dimensions of matrix_data_1: ", np.ndim(matrix_data_1)) # Output: 2 as function

print("=================================")

Dimensions of matrix_data_1:  2
Dimensions of matrix_data_1:  2


In [9]:
# len function is used to get the length of an array.

print("Length:", len(matrix_data_1))          # 3 (number of rows)

print("=================================")

# size property is used to get the **total number of elements** in a NumPy array.

print("Total elements:", e.size)  # 4 (2 × 2)

Length: 3
Total elements: 4


In [10]:
# shape property and np.shape() function are used to get the shape of an array.

print("Shape of matrix_data_1: ", matrix_data_1.shape) # Output: (3, 3) as property

print("=================================")

print("Shape of matrix_data_1: ", np.shape(matrix_data_1)) # Output: (3, 3) as function

print("=================================")

Shape of matrix_data_1:  (3, 3)
Shape of matrix_data_1:  (3, 3)


In [11]:
# reshape() function is used to change the shape of an array without changing its data.

reshaped_matrix = matrix_data_1.reshape(1, 9) # Reshaping to 1 row and 9 columns

print("Reshaped Matrix (1 x 9): ", reshaped_matrix) # Output: row vector with 9 elements

# 2. vstack (Vertical Stack): Stacks arrays on top of each other (increases rows).
# Think of it as "Adding more samples".
v_stacked = np.vstack((matrix_data_1, matrix_data_2))

print("Vertical Stack (vstack):\n", v_stacked)

print("---------------------------------")

# 3. hstack (Horizontal Stack): Stacks arrays side-by-side (increases columns).
# Think of it as "Adding more features".
h_stacked = np.hstack((matrix_data_1, matrix_data_2))

print("Horizontal Stack (hstack):\n", h_stacked)

print("=======================================================")

Reshaped Matrix (1 x 9):  [[1 2 3 4 5 6 7 8 9]]
Vertical Stack (vstack):
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
---------------------------------
Horizontal Stack (hstack):
 [[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


In [12]:
# Example of reshaping a vector to a matrix

vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape(2, 3)  # Reshaping to 2 rows and 3 columns, must match total elements

print("Reshaped Vector to Matrix (2 x 3): \n", mat) # Output: 2 x 3 matrix

print("=================================")

print("Rows: ", mat.shape[0], ", Columns: ", mat.shape[1]) # used to get rows and columns

Reshaped Vector to Matrix (2 x 3): 
 [[1 2 3]
 [4 5 6]]
Rows:  2 , Columns:  3


In [13]:
mat = vec[:, None]  # Converting to a column vector
print("Column Vector: \n", mat)

print("=================================")

mat = vec[None, :]  # Converting to a row vector
print("Row Vector: \n", mat)

Column Vector: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Row Vector: 
 [[1 2 3 4 5 6]]


In [14]:
# dtype property is used to get the data type of an array

print("Data type of vector_data_1: ", vector_data_1.dtype)

print("=================================")

print("Data type of matrix_data_1: ", matrix_data_1.dtype)

Data type of vector_data_1:  int64
Data type of matrix_data_1:  int64


In [15]:
# priority of data types: object < string < float < int < bool

vec_mixed = np.array([1, 2.5, 3, 1])

print("Data type of mixed vector: ", vec_mixed.dtype) # Output: string (all elements converted to string)

Data type of mixed vector:  float64


In [16]:
vec_mixed = vec_mixed.astype(int)  # Converting back to object type


print("after converting back to int: ", vec_mixed)

print("=================================")

print("Data type after converting back to object: ", vec_mixed.dtype)

after converting back to int:  [1 2 3 1]
Data type after converting back to object:  int64


In [17]:
# Copying arrays

i = a.view() # Create a view of the array with the same data

j = np.copy(a) # Create a copy of the array

k = a.copy() # Create a deep copy of the array

In [18]:
print("Original array a: \n", a)

print("=================================")

print("View i: \n", i)

print("=================================")

print("Copy using np.copy() j: \n", j)

print("=================================")

print("Deep copy using a.copy() k: \n", k)

print("=================================")

Original array a: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
View i: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Copy using np.copy() j: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Deep copy using a.copy() k: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
print("Original array:\n", matrix_data_2)

print("=================================")

s1 = matrix_data_2.copy()
s1.sort()
print("Sorted completely (each row sorted):\n", s1)

print("=================================")

s2 = matrix_data_2.copy()
s2.sort(axis=0)
print("Sorted by columns (axis=0):\n", s2)

print("=================================")

Original array:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Sorted completely (each row sorted):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Sorted by columns (axis=0):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [20]:
# Creating a 2D array (2 rows, 4 columns)
l = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Original Array (l):\n", l)

print("=================================")

# 1. Get specific element [Row, Column]
# Remember: Indexing starts at 0. [1, 3] means 2nd row, 4th column.
element = l[1, 3]

print("Specific Element at [1, 3]:", element) # Should be 8

print("=================================")

# 2. Get specific row
# The colon ':' means "all"
row = l[0, :]

print("First Row (l[0, :]):", row) # [1, 2, 3, 4]

print("=================================")

# 3. Get specific column
column = l[:, 2]

print("Third Column (l[:, 2]):", column) # [3, 7]

print("=================================")

# 4. Getting fancy [start : end : step]
# This says: start(num), end(num), jump by 2.
# Note: Since the range is only 1 element wide, step won't do much here!
fancy_slice = l[0, 1:4:2] 

print("Fancy Slice (Row 0, elements from index 1 to 4, step 2):", fancy_slice) # [2, 4]

print("=================================")

# 5. Changing elements (Direct Mutation)
l[1, 2] = 20

print("Array after changing [1, 2] to 20:\n", l)

print("=================================")

l[:, 3] = [9, 10]

print("Array after changing the whole last column:\n", l)

print("=================================")

Original Array (l):
 [[1 2 3 4]
 [5 6 7 8]]
Specific Element at [1, 3]: 8
First Row (l[0, :]): [1 2 3 4]
Third Column (l[:, 2]): [3 7]
Fancy Slice (Row 0, elements from index 1 to 4, step 2): [2 4]
Array after changing [1, 2] to 20:
 [[ 1  2  3  4]
 [ 5  6 20  8]]
Array after changing the whole last column:
 [[ 1  2  3  9]
 [ 5  6 20 10]]


In [21]:
# Creating a 3D array (2 blocks, 2 rows, 2 columns)
m = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Original 3D Array (m):\n", m)

print("=================================")

# 1. Get specific element (Work outside-in)
# Index [0, 1, 1] means:
# Block 0 (First matrix)
# Row 1 (Second row of that matrix)
# Column 1 (Second element of that row)
element = m[0, 1, 1]

print("Specific Element at [0, 1, 1]:", element) # Should be 4

print("=================================")

# 2. Replacing elements (Direct Mutation)
# This targets:
# [:] -> All blocks (both matrices)
# [1] -> Only the second row (Row Index 1)
# [:] -> All columns in those rows
m[:, 1, :] = [[9, 9], [8, 8]]

print("Array after replacing the second row of each block:\n", m)

print("=================================")

# 3. Fancy check: Get the first column of every block
# [:]   -> Both blocks
# [:]   -> All rows
# [0]   -> Only the first column
first_columns = m[:, :, 0]

print("First column of all blocks (m[:, :, 0]):\n", first_columns)

print("=================================")

Original 3D Array (m):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Specific Element at [0, 1, 1]: 4
Array after replacing the second row of each block:
 [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
First column of all blocks (m[:, :, 0]):
 [[1 9]
 [5 8]]


In [26]:
arr = np.array([1,2,3])

np.where(arr > 2, 5, 2)

array([2, 2, 5])